services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  microservice:
    build: .
    container_name: microservice-alojamiento-pago
    depends_on:
      - mongodb
    ports:
      - "8080:8080"  # Cambia el puerto aquí a 8080
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/universidad
      - PORT=8080  # Añade esta línea para pasar el puerto correcto
    volumes:
      - ./data:/app/data
    command: ["node", "src/app.js"]  # Asegúrate de que app.js es el punto de entrada correcto

volumes:
  mongo-data:
